language: go

go:
  - 1.8

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install
  - chmod +x ./test.sh

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
